document.write("<html>");
document.write("<head>");
document.write("<script src=\"https:\/\/cdn.socket.io\/socket.io-1.2.0.js\"><\/script>");
document.write("<link rel=\"stylesheet\" href=\"http:\/\/fonts.googleapis.com\/css?family=Droid+Sans:400,700\">");
document.write("  <style>");
document.write("");
document.write("body {");
document.write("  background: #e9e9e9;");
document.write("  color: #9a9a9a;");
document.write("  font: 100%\/1.5em \"Droid Sans\", sans-serif;");
document.write("  margin: 0;");
document.write("}");
document.write("");
document.write("a { text-decoration: none; }");
document.write("");
document.write("fieldset {");
document.write("  border: 0;");
document.write("  margin: 0;");
document.write("  padding: 0;");
document.write("}");
document.write("");
document.write("h4, h5 {");
document.write("  line-height: 1.5em;");
document.write("  margin: 0;");
document.write("}");
document.write("");
document.write("hr {");
document.write("  background: #e9e9e9;");
document.write("    border: 0;");
document.write("    -moz-box-sizing: content-box;");
document.write("    box-sizing: content-box;");
document.write("    height: 1px;");
document.write("    margin: 0;");
document.write("    min-height: 1px;");
document.write("}");
document.write("");
document.write("img {");
document.write("    border: 0;");
document.write("    display: block;");
document.write("    height: auto;");
document.write("    max-width: 100%;");
document.write("}");
document.write("");
document.write("input {");
document.write("  border: 0;");
document.write("  color: inherit;");
document.write("    font-family: inherit;");
document.write("    font-size: 100%;");
document.write("    line-height: normal;");
document.write("    margin: 0;");
document.write("}");
document.write("");
document.write("p { margin: 0; }");
document.write("");
document.write(".clearfix { *zoom: 1; } \/* For IE 6\/7 *\/");
document.write(".clearfix:before, .clearfix:after {");
document.write("    content: \"\";");
document.write("    display: table;");
document.write("}");
document.write(".clearfix:after { clear: both; }");
document.write("");
document.write("\/* ---------- LIVE-CHAT ---------- *\/");
document.write("");
document.write("#live-chat {");
document.write("  bottom: 0;");
document.write("  font-size: 12px;");
document.write("  right: 24px;");
document.write("  position: fixed;");
document.write("  width: 300px;");
document.write("}");
document.write("");
document.write("#live-chat header {");
document.write("  background: #293239;");
document.write("  border-radius: 5px 5px 0 0;");
document.write("  color: #fff;");
document.write("  cursor: pointer;");
document.write("  padding: 16px 24px;");
document.write("}");
document.write("");
document.write("#live-chat h4:before {");
document.write("  background: #1a8a34;");
document.write("  border-radius: 50%;");
document.write("  content: \"\";");
document.write("  display: inline-block;");
document.write("  height: 8px;");
document.write("  margin: 0 8px 0 0;");
document.write("  width: 8px;");
document.write("}");
document.write("");
document.write("#live-chat h4 {");
document.write("  font-size: 12px;");
document.write("}");
document.write("");
document.write("#live-chat h5 {");
document.write("  font-size: 10px;");
document.write("}");
document.write("");
document.write("#live-chat form {");
document.write("  padding: 24px;");
document.write("}");
document.write("");
document.write("#live-chat input[type=\"text\"] {");
document.write("  border: 1px solid #ccc;");
document.write("  border-radius: 3px;");
document.write("  padding: 8px;");
document.write("  outline: none;");
document.write("  width: 90%;");
document.write("  margin-bottom: 10px;");
document.write("}");
document.write("");
document.write(".chat-message-counter {");
document.write("  background: #e62727;");
document.write("  border: 1px solid #fff;");
document.write("  border-radius: 50%;");
document.write("  font-size: 12px;");
document.write("  font-weight: bold;");
document.write("  height: 28px;");
document.write("  left: 0;");
document.write("  line-height: 28px;");
document.write("  margin: -15px 0 0 -15px;");
document.write("  position: absolute;");
document.write("  text-align: center;");
document.write("  top: 0;");
document.write("  width: 28px;");
document.write("}");
document.write("");
document.write(".chat-close {");
document.write("  background: #1b2126;");
document.write("  border-radius: 50%;");
document.write("  color: #fff;");
document.write("  display: block;");
document.write("  float: right;");
document.write("  font-size: 10px;");
document.write("  height: 16px;");
document.write("  line-height: 16px;");
document.write("  margin: 2px 0 0 0;");
document.write("  text-align: center;");
document.write("  width: 16px;");
document.write("}");
document.write("");
document.write(".chat {");
document.write("  background: #fff;");
document.write("  display: none;");
document.write("}");
document.write("");
document.write(".chat-history {");
document.write("  height: 252px;");
document.write("  padding: 8px 24px;");
document.write("  overflow-y: scroll;");
document.write("}");
document.write("");
document.write(".chat-message {");
document.write("  margin: 16px 0;");
document.write("}");
document.write("");
document.write(".chat-message img {");
document.write("  border-radius: 50%;");
document.write("  float: left;");
document.write("}");
document.write("");
document.write(".chat-message-content {");
document.write("  margin-left: 56px;");
document.write("}");
document.write("");
document.write(".chat-time {");
document.write("  float: right;");
document.write("  font-size: 10px;");
document.write("}");
document.write("");
document.write(".chat-feedback {");
document.write("  display: none;");
document.write("}");
document.write("  <\/style>");
document.write("");
document.write("<\/head>");
document.write("<script type=\"text\/javascript\">");
document.write("");
document.write("  function openLiveChatHeader () {");
document.write("    $('.chat').slideToggle(300, 'swing');");
document.write("    $('.chat-message-counter').fadeToggle(300, 'swing');");
document.write("    var list =  document.getElementById('chat-list-'+i);");
document.write("    list.scrollIntoView();");
document.write("  }");
document.write("      var i=0;");
document.write("      var socket = io();");
document.write("      function send() {");
document.write("          i++;");
document.write("          $('.chat-feedback').show();");
document.write("          var msg = $('#btn-input').val();");
document.write("          var time  = new Date();");
document.write("          socket.emit('chat message', $('#btn-input').val());");
document.write("          $('#chat-id').append('<div id=\"chat-list-'+i+'\" class=\"chat-message clearfix\"><img src=\"\/people-512.png\" alt=\"\" width=\"32\" height=\"32\"><div class=\"chat-message-content clearfix\"><span class=\"chat-time\"><\/span><h5>Customer<\/h5> <p>'+msg+'<\/p> <\/div><\/div><hr>');");
document.write("          $('#btn-input').val('');");
document.write("          var list =  document.getElementById('chat-list-'+i);");
document.write("          list.scrollIntoView();");
document.write("          return false;");
document.write("      }");
document.write("");
document.write("");
document.write("      socket.on('chat message', function(msg){");
document.write("        i++;");
document.write("        $('.chat-feedback').hide();");
document.write("        $('#chat-id').append('<div  id=\"chat-list-'+i+'\" class=\"chat-message clearfix\"><img src=\"\/bot-de-telegram.jpg\" alt=\"\" width=\"32\" height=\"32\"><div class=\"chat-message-content clearfix\"><span class=\"chat-time\"><\/span><h5>Bõtola<\/h5> <p>'+msg+'<\/p> <\/div><\/div><hr>');");
document.write("        var list =  document.getElementById('chat-list-'+i);");
document.write("        list.scrollIntoView();");
document.write("      });");
document.write("");
document.write("<\/script>");
document.write("<body>");
document.write("  <div id=\"live-chat\">");
document.write("    <header class=\"clearfix\" onclick=\"openLiveChatHeader()\">");
document.write("      <h4>Bõtola<\/h4>");
document.write("      <span class=\"chat-message-counter\">1<\/span>");
document.write("    <\/header>");
document.write("");
document.write("    <div class=\"chat\">");
document.write("      <div id=\"chat-id\" class=\"chat-history\">");
document.write("        <div  id=\"chat-list-0\" class=\"chat-message clearfix\"><img src=\"\/bot-de-telegram.jpg\" alt=\"\" width=\"32\" height=\"32\"\/><div class=\"chat-message-content clearfix\"><span class=\"chat-time\"><\/span><h5>Bõtola<\/h5> <p>Hey, This is Bõtola, How may I help you?<\/p> <\/div><\/div><hr>");
document.write("      <\/div>");
document.write("      <div align=\"center\">");
document.write("       <img class=\"chat-feedback\" src=\"\/hex-loader2.gif\" alt=\"\" width=\"40\" height=\"40\"\/>");
document.write("       <div class=\"clearfix\">");
document.write("        <input id=\"btn-input\" type=\"text\" onkeydown = \"if (event.keyCode == 13)");
document.write("        send()\" class=\"form-control input-sm\" placeholder=\"Type your message here...\" autofocus\/>");
document.write("      <\/div>");
document.write("    <\/div>");
document.write("");
document.write("  <\/div>");
document.write("  <script src=\"\/\/ajax.googleapis.com\/ajax\/libs\/jquery\/2.0.2\/jquery.min.js\"><\/script>");
document.write("<\/body>");
document.write("<\/html>");